name: Run E2E Tests with TestContainers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: '24'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: docker/setup-buildx-action@v2

      - name: Run E2E Tests
        run: pnpm run test:e2e
        env:
          NODE_ENV: test
